### ISSUE TITLE
Cannot run it on Kibana 5

### ISSUE THREAD

**Issue by dmkog** [chenryn/kbn_sankey_vis#11]
Whn I try  to run Kibana 5.1.1 after cloning this to the kibana plugins folder I cannot run Kibana any more until I uninstall this visualization.

The error when I try to run Kibana is:

FATAL TypeError: Cannot read property 'error' of undefined
    at OptionManager.mergeOptions (/usr/share/kibana/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:28)
    at OptionManager.addConfig (/usr/share/kibana/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
    at OptionManager.findConfigs (/usr/share/kibana/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:35)
    at OptionManager.init (/usr/share/kibana/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at compile (/usr/share/kibana/node_modules/babel-core/lib/api/register/node.js:117:22)
    at normalLoader (/usr/share/kibana/node_modules/babel-core/lib/api/register/node.js:199:14)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/share/kibana/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Plugins.<anonymous> (/usr/share/kibana/src/server/plugins/plugin_collection.js:66:30)
    at undefined.next (native)
    at step (/usr/share/kibana/src/server/plugins/plugin_collection.js:22:273)
    at /usr/share/kibana/src/server/plugins/plugin_collection.js:22:443

**Comment by muruga** [comment]
i tried with kibana 5.1.2, getting the above error

**Comment by AdrianP-** [comment]
Same here :(

**Comment by JuanCarniglia** [comment]
I just released a Kibana 6.0.0-alpha1 version of this plugin (Actually, a clone of this one).

https://github.com/JuanCarniglia/kbn_sankey_vis

Let me know if it works for you guys.

Thanks!

**Comment by WolfangAukang** [comment]
@JuanCarniglia your solution has a problem when running npm run build. It asks for babel-register, and even installing it, it gives the same error.

And on your README file, the instructions are pointing to clone to this repo instead of yours. Just to fix that :)

**Comment by WolfangAukang** [comment]
@muruga @khubdm2 @AdrianP- I got it working on Kibana 5.2.1. I based the code on @JuanCarniglia repo with the latest build he did for 6.0.0-alpha. The repo is https://github.com/WolfangAukang/kbn_sankey_vis

**Comment by rcfontana** [comment]
Has anyone tried this with 5.4.1 ? I tried (for 5 minutes..) chenryn, JuanCarniglia and WolfangAukang and I'm getting all sort of errors.

**Comment by WolfangAukang** [comment]
@rcfontana What kind of error are you receiving? I can help you

EDIT: Have you changed the version at the package.json to the version you are using?

**Comment by JuanCarniglia** [comment]
Please paste the error result here. It might be a missing dependency or maybe a wrong path (A lot of them changed from 4.x to 5.x and to 6.x, but I don't believe many changed from 5.2.1 to 5.4.x.

**Comment by rcfontana** [comment]
cd KIBANA_HOME/plugins
git clone https://github.com/JuanCarniglia/kbn_sankey_vis 
Changed the package.json to 5.4.1

Now I'm getting husky issues.

some WARN issues:
npm WARN package.json kbn_sankey_vis@5.4.1 No repository field.
npm WARN engine husky@0.14.1: wanted: {"node":">=4"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine strip-indent@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.29","npm":"1.4.21"})
...
...
npm ERR! husky@0.14.1 install: `node ./bin/install.js`
npm ERR! Exit status 127
npm ERR!
npm ERR! Failed at the husky@0.14.1 install script.
npm ERR! This is most likely a problem with the husky package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls husky
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "husky"
npm ERR! cwd /usr/share/kibana/plugins/kbn_sankey_vis
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /usr/share/kibana/plugins/kbn_sankey_vis/npm-debug.log
npm ERR! not ok code 0

**Comment by scottwallred** [comment]
Trying to get this working with Kibana 5.2.2.  

Have tired both the https://github.com/JuanCarniglia/kbn_sankey_vis and https://github.com/WolfangAukang/kbn_sankey_vis.  

Getting this error on kibana:

/elk/bundles/commons.bundle.js?v=14723:38 TypeError: _d32.default.sankey is not a function
    at _buildVis (/elk/bundles/kibana.bundle.js?v=14723:162)
    at Object.fn (/elk/bundles/kibana.bundle.js?v=14723:162)
    at Scope.$digest (/elk/bundles/commons.bundle.js?v=14723:39)
    at Scope.$apply (/elk/bundles/commons.bundle.js?v=14723:39)
    at done (/elk/bundles/commons.bundle.js?v=14723:37)
    at completeRequest (/elk/bundles/commons.bundle.js?v=14723:37)
    at XMLHttpRequest.xhr.onload (/elk/bundles/commons.bundle.js?v=14723:37)

**Comment by kaihil** [comment]
I just installed the plugin on 5.3.3 via https://github.com/WolfangAukang/kbn_sankey_vis

@chenryn: Is there a chance to merge his contribution into this main repo? Would be great to have a working installation process :) Or did you stop maintaining?

**Comment by WolfangAukang** [comment]
@chenryn I can do the pull request

@kaihil Did you have to follow any other steps besides the ones indicated on the repo? It's because some people could not install it, so I don't know if there is something missing or not.

**Comment by kaihil** [comment]
No, i just cloned the repo and adapted the "version" in the package.json. After restarting kibana, it worked!

**Comment by chenryn** [comment]
@kaihil PR is welcome.

**Comment by kaihil** [comment]
@WolfangAukang: Could you do that PR? I'm not really into this kibana plugin stuff, but would highly appreciate it :)

**Comment by WolfangAukang** [comment]
Sure, let me do some stuff (I have cloned it from JuanCarniglia instead of Chenryn) and I will be ready for the pull request

**Comment by nagmar** [comment]
Hey guys , there is someone why uses this pluging with kibana 5.5 ?

**Comment by akefallonitis** [comment]
Not working on 5.5.0 both repos

**Comment by JuanCarniglia** [comment]
Just committed a working version for Kibana 5.5 on my http://github.com/JuanCarniglia/kbn_sankey_vis, check the releases folder.
